In [1]:
import pandas as pd
import glob

files = glob.glob("C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets/*.xlsx")
print(files)

['C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2010-2011.xlsx', 'C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2012-2013.xlsx', 'C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2014-2015.xlsx', 'C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2016-2017.xlsx', 'C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2018-19.xlsx', 'C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2020-21.xlsx', 'C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2022-23.xlsx', 'C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2024-25.xlsx', 'C:/Users/Aditi Bajpai/Documents/DataAnalystPrep/datasets\\_Bank Credit of SCBs - Bank Group, Population Group, Occupation (Sector), District Wise - Annual-2026.xlsx']

In [2]:
df = pd.read_excel(files[0])
print(df.shape)
print(df.columns.tolist())
df.head()

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

(188485, 13)
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,"Bank Group wise, district wise, population gro...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"Note: For Exporting Data into Excel, ensure th...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Year,Region (Utilization),State (Utilization),District (Utilization),NaN,Population Group - Utilization,Bank Group New,Occupation Group,Occupation Sub- Group,No. of Accounts,Credit Limit (in Rs Crores),Amount Outstanding (in Rs Crores)

In [3]:
df = pd.read_excel(files[0], skiprows=4)
print(df.shape)
print(df.columns.tolist())
df.head()

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

(188481, 13)
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,Year,Region (Utilization),State (Utilization),District (Utilization),NaN,Population Group - Utilization,Bank Group New,Occupation Group,Occupation Sub- Group,No. of Accounts,Credit Limit (in Rs Crores),Amount Outstanding (in Rs Crores)
1,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,5. Personal Credit Cards,398,1.9978,1.101
2,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,3. Vehicles,1078,32.9539,25.1907
3,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,4. Education,369,12.0295,8.3041
4,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,6. Others,5332,94.2223,69.2429

In [4]:
df = pd.read_excel(files[0], header=5)
print(df.shape)
print(df.columns.tolist())
df.head()

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

(188480, 13)
['Unnamed: 0', 'Year', 'Region (Utilization)', 'State (Utilization)', 'District (Utilization)', 'Unnamed: 5', 'Population Group - Utilization', 'Bank Group New', 'Occupation Group', 'Occupation Sub- Group', 'No. of Accounts', 'Credit Limit (in Rs Crores)', 'Amount Outstanding (in Rs Crores)']

,Unnamed: 0,Year,Region (Utilization),State (Utilization),District (Utilization),Unnamed: 5,Population Group - Utilization,Bank Group New,Occupation Group,Occupation Sub- Group,No. of Accounts,Credit Limit (in Rs Crores),Amount Outstanding (in Rs Crores)
0,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,5. Personal Credit Cards,398,1.9978,1.1010
1,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,3. Vehicles,1078,32.9539,25.1907
2,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,4. Education,369,12.0295,8.3041
3,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,6. Others,5332,94.2223,69.2429
4,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,1. Housing,1785,121.7306,96.8150

In [5]:
df = pd.read_excel(files[0], header=5)
print(df.shape)
print(df.columns.tolist())
df.head()

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

(188480, 13)
['Unnamed: 0', 'Year', 'Region (Utilization)', 'State (Utilization)', 'District (Utilization)', 'Unnamed: 5', 'Population Group - Utilization', 'Bank Group New', 'Occupation Group', 'Occupation Sub- Group', 'No. of Accounts', 'Credit Limit (in Rs Crores)', 'Amount Outstanding (in Rs Crores)']

,Unnamed: 0,Year,Region (Utilization),State (Utilization),District (Utilization),Unnamed: 5,Population Group - Utilization,Bank Group New,Occupation Group,Occupation Sub- Group,No. of Accounts,Credit Limit (in Rs Crores),Amount Outstanding (in Rs Crores)
0,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,5. Personal Credit Cards,398,1.9978,1.1010
1,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,3. Vehicles,1078,32.9539,25.1907
2,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,4. Education,369,12.0295,8.3041
3,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,6. Others,5332,94.2223,69.2429
4,NaN,2011,CENTRAL REGION,CHHATTISGARH,BASTAR,NaN,SEMI-URBAN,PUBLIC SECTOR BANKS,V. PERSONAL LOANS,1. Housing,1785,121.7306,96.8150

In [6]:
df = df.drop(columns=['Unnamed: 0', 'Unnamed: 5'])
print(df.shape)
print(df.columns.tolist())

(188480, 11)
['Year', 'Region (Utilization)', 'State (Utilization)', 'District (Utilization)', 'Population Group - Utilization', 'Bank Group New', 'Occupation Group', 'Occupation Sub- Group', 'No. of Accounts', 'Credit Limit (in Rs Crores)', 'Amount Outstanding (in Rs Crores)']

In [ ]:
all_data = []

for f in files:
    temp = pd.read_excel(f, header=5)
    temp = temp.dropna(axis=1, how='all')      # drop fully-empty columns
    all_data.append(temp)
    print(f"Loaded {f[-20:]} — {temp.shape}")

df = pd.concat(all_data, ignore_index=True)
print("COMBINED:", df.shape)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Loaded nnual-2010-2011.xlsx — (188480, 11)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Loaded nnual-2012-2013.xlsx — (192386, 11)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Loaded nnual-2014-2015.xlsx — (205883, 11)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Loaded nnual-2016-2017.xlsx — (222264, 11)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Loaded  Annual-2018-19.xlsx — (278894, 11)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Loaded  Annual-2020-21.xlsx — (301269, 11)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Loaded  Annual-2022-23.xlsx — (326951, 11)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Loaded  Annual-2024-25.xlsx — (348785, 11)

C:\Users\Aditi Bajpai\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
df.to_csv("bsr1_combined.csv", index=False)
print("saved")

In [ ]:
print(sorted(df['Year'].unique()))

In [ ]:
df.to_csv("bsr1_combined.csv", index=False)

In [ ]:
df.to_csv("bsr1_combined.csv", index=False)

In [17]:
import pandas as pd
df = pd.read_csv("bsr1_combined.csv")
print(df.shape)
print(sorted(df['Year'].unique()))

(2244711, 11)
[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]

In [19]:
print(df.shape)
print(sorted(df['Year'].unique()))

(2244711, 11)
[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]

In [20]:
df.isnull().sum()

Year                                      0
Region (Utilization)                      4
State (Utilization)                       4
District (Utilization)                    4
Population Group - Utilization            0
Bank Group New                            0
Occupation Group                          0
Occupation Sub- Group                224796
No. of Accounts                           4
Credit Limit (in Rs Crores)               4
Amount Outstanding (in Rs Crores)         4
dtype: int64

In [21]:
df[df['State (Utilization)'].isnull()]

,Year,Region (Utilization),State (Utilization),District (Utilization),Population Group - Utilization,Bank Group New,Occupation Group,Occupation Sub- Group,No. of Accounts,Credit Limit (in Rs Crores),Amount Outstanding (in Rs Crores)
94587,2011,NaN,NaN,NaN,METROPOLITAN,PUBLIC SECTOR BANKS,II. INDUSTRY,4. Textiles,0.0,0.0,0.0
94588,2011,NaN,NaN,NaN,URBAN,PUBLIC SECTOR BANKS,II. INDUSTRY,"17. Electricity, Gas & Water",0.0,0.0,0.0
94589,2011,NaN,NaN,NaN,URBAN,PUBLIC SECTOR BANKS,II. INDUSTRY,2. Food Manufacturing & Processing,0.0,0.0,0.0
94590,2011,NaN,NaN,NaN,RURAL,REGIONAL RURAL BANKS,II. INDUSTRY,3. Beverage & Tobacco,0.0,0.0,0.0

In [22]:
df = df.dropna(subset=['State (Utilization)'])
print(df.shape)

(2244707, 11)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2244707 entries, 0 to 2244710
Data columns (total 11 columns):
 #   Column                             Dtype
---  ------                             -----
 0   Year                               int64
 1   Region (Utilization)               object
 2   State (Utilization)                object
 3   District (Utilization)             object
 4   Population Group - Utilization     object
 5   Bank Group New                     object
 6   Occupation Group                   object
 7   Occupation Sub- Group              object
 8   No. of Accounts                    float64
 9   Credit Limit (in Rs Crores)        float64
 10  Amount Outstanding (in Rs Crores)  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 205.5+ MB

In [27]:
df.nunique()

Year                                     17
Region (Utilization)                      6
State (Utilization)                      40
District (Utilization)                  825
Population Group - Utilization            5
Bank Group New                           14
Occupation Group                          8
Occupation Sub- Group                    33
No. of Accounts                       44974
Credit Limit (in Rs Crores)          602441
Amount Outstanding (in Rs Crores)    542545
dtype: int64

In [28]:
df['Population Group - Utilization'].unique()

array(['SEMI-URBAN', 'RURAL', 'URBAN', 'METROPOLITAN', 'SEMI URBAN'],
      dtype=object)

In [29]:
df['Population Group - Utilization'] = df['Population Group - Utilization'].replace('SEMI URBAN', 'SEMI-URBAN')
print(df['Population Group - Utilization'].unique())

['SEMI-URBAN' 'RURAL' 'URBAN' 'METROPOLITAN']